app/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
# from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
# from .views import Tour_cities
from simplecitytours import views

urlpatterns = [
    # url(r'login/', obtain_jwt_token),
    # url(r'verify_token/', verify_jwt_token),
    # url(r'logout/', refresh_jwt_token),
    # url(r'testapi/', views.test_resp, name='testresp'),
    url(r'signup/', views.signup_user, name='signup'),
    url(r'getaudio/', views.get_audio, name='audio'),
    url(r'get_imgs/', views.get_cities_imgs, name='imgs'),
    url(r'check_update/', views.check_sequence, name='check-update'),
    url(r'get_points/', views.get_points, name='points'),
    url(r'get_all_locations/', views.get_all_locations, name='get-locations'),
    # url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'types/', views.getPointTypes, name='check-types'),
]

simplecitytours/urls.py
"""
Definition of urls for simplecitytours.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.conf import settings
from django.conf.urls.static import static

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from rest_framework import routers
from .views import UserViewSet, PolygonViewSet, LandingPageViewSet, LocationViewSet, PointTypeViewSet, PointViewSet, TouristViewSet, UserPaymentViewSet, AdminActiveTimeViewSet
from rest_framework import routers, serializers, viewsets

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'polygon', PolygonViewSet)
router.register(r'landingpage', LandingPageViewSet)
router.register(r'location', LocationViewSet)
router.register(r'pointtype', PointTypeViewSet)
router.register(r'point', PointViewSet)
router.register(r'tourist', TouristViewSet)
router.register(r'userpayment', UserPaymentViewSet)
router.register(r'adminactivetime', AdminActiveTimeViewSet)

urlpatterns = [
    url(r'^$', app.views.home, name='home'),
    url(r'^locations/$', app.views.locations, name='locations'),
    url(r'^map/$', app.views.map, name='map'),
    url(r'^users/$', app.views.users, name='users'),
    url(r'^userCreation/$', app.views.userCreation.as_view(), name='userCreation'),
    url(r'^cityedit/(?P<pk>[0-9]+)/update/$', app.views.cityedit.as_view(), name='cityedit'),
    url(r'^user/(?P<pk>[0-9]+)/update/$', app.views.userUpdate.as_view(), name='userUpdate'),
    url(r'^user/(?P<pk>[0-9]+)/test/$', app.views.userUpdate.get_context_data, name='userTest'),
    url(r'^user/(?P<pk>[0-9]+)/delete/$', app.views.userDelete.as_view(), name='userDelete'),
    url(r'^user/(?P<pk>[0-9]+)/password/$', app.views.changePassword.as_view(), name='changePassword'),
    url(r'^createCity/$', app.views.createCity, name='createCity'),
    url(r'^createPolygon/$', app.views.createPolygon, name='createPolygon'),
    url(r'^updatePolygon/$', app.views.updatePolygon, name='updatePolygon'),
    url(r'^city/(?P<pk>[0-9]+)/$', app.views.DetailView.as_view(), name='city'),
    url(r'^cityUpdate/(?P<pk>[0-9]+)/$', app.views.cityUpdate.as_view(), name='cityUpdate'),
    url(r'^cityUpdateAdmin/(?P<pk>[0-9]+)/$', app.views.cityUpdateAdmin.as_view(), name='cityUpdateAdmin'),
    url(r'^cityDelete/(?P<pk>[0-9]+)/delete/$', app.views.cityDelete.as_view(), name='cityDelete'),
    url(r'^cityPolygonUpdate/(?P<pk>[0-9]+)/$', app.views.cityPolygonUpdate, name='cityPolygonUpdate'),
    url(r'^cityPointsUpdate/(?P<pk>[0-9]+)/$', app.views.cityPointsUpdate, name='cityPointsUpdate'),
    url(r'^deletePoint/$', app.views.deletePoint, name='deletePoint'),
    url(r'^createPoint/$', app.views.createPoint, name='createPoint'),
    url(r'^payment/$', app.views.payment, name='payment'),
    url(r'^audio/$', app.views.audio, name='audio'),
    url(r'^about', app.views.about, name='about'),
    url(r'^purchase/', app.views.purchase, name='purchase'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Login',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^app/', include('app.urls')),
     url(r'^api/', include(router.urls)),
     url(r'^rest-auth/', include('rest_auth.urls')),
     url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from .models import Location

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


class UserForm(forms.ModelForm):
    """form for user creation"""
    email = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'email'}))
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Username'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
    class Meta:
        model = User
        fields = ['username', 'password' , 'email']


class PasswordForm(forms.ModelForm):
    """form for password change"""
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
    class Meta:
        model = User
        fields = ['password']


class CityForm(forms.ModelForm):
    """form for user creation"""
    name = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'name'}))
    description = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'description'}))
    price = forms.CharField(label=_("Password"),
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder':'price'}))
    class Meta:
        model = Location
        fields = ['name', 'description' , 'price']

app/templates/app/MapPolygonUpdate.html
{% extends "app/layout.html" %}

{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<h1>Create City Map</h1>

<div>
    <div id="map" style="height: 100vh; width: 100vw; max-width: 100%;"></div>
</div>

<div class="container" style="margin-top:30px;">
    <form>
        <div class="pull-right">
            <button type="button" class="btn btn-primary" onclick="createMap()">Create Map</button>
            <button type="button" class="btn btn-danger" onClick="window.location.reload()">Cancel</button>
        </div>
    </form>
</div>

<script>

    var map;
    var newPolygons = [];
    var infoWindow;


    var listvalues = localStorage.getItem('lists');
    //parse the value
    var finalvalue = JSON.parse(listvalues);

    //Create Map Function on Button Click
    function createMap() {
      //city = document.getElementById('citynameInput').value;
      //description = document.getElementById('descriptionInput').value;
      //img = document.getElementById('imgInput').value;
      //Map Options
      var newOptions = {
        zoom: map.zoom,
        center: map.center
      }

      //Overwrite Existing map
      map = new google.maps.Map(document.getElementById('map'), newOptions);

      //Add Polygons
      var polygon = new google.maps.Polygon(newPolygons);
      polygon.setMap(map);

      //coordinates of the polygon
      var coordinates = polygon.getPath().getArray();
      console.log(coordinates);

      //Show Name and Description on Click
      polygon.addListener('click', function(event) {
        infoWindow = new google.maps.InfoWindow;
        infoWindow.setContent("<b>" + city + "</b><br />" + description);
        infoWindow.setPosition(event.latLng);
        infoWindow.open(map);
      });

      $.ajax({
            "type": "POST",
            "url": "/updatePolygon/",
            "data": {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                name: '{{city.name}}',
                points: JSON.stringify(coordinates),
                strokeColor: '#cccc00',
                strokeOpacity: 1.0,
                strokeWeight: 3,
                fillColor: 'yellow',
                fillOpacity: 0.05
            },
            "success": function (result) {
                console.log(result);
            },
            "error": function (xhr, status, error) {
                console.log(xhr);
                console.log(status);
                console.log(error);
            },
        });
    }

    //Initial Map
    function initMap() {
        //map options
        var defaultOptions = {
            zoom: parseInt('{{ city.zoom }}'),
            center: {
                lat: parseInt('{{ city.lat }}'),
                lng: parseInt('{{ city.lng }}')
            }
        }

        //create map
        map = new google.maps.Map(document.getElementById('map'), defaultOptions);

        var points = '{{ polygon }}';
        points = points.replace(/&quot;/g, '"');
        points = JSON.parse(points);
        //polygon defaults
        poly = new google.maps.Polygon({
            path: points,
            strokeColor: '#cccc00',
            strokeOpacity: 1.0,
            strokeWeight: 3,
            fillColor: 'yellow',
            fillOpacity: 0.3,
            editable: true
        });
        poly.setMap(map);
        newPolygons = poly;


        // Listen from click on map
        google.maps.event.addListener(map, 'click',
            function (event) {
                debugger
                var path = poly.getPath();
                console.log("test");

                //creates polygon once 5 points are chosen
                if (path.length == 4) {
                    var polygonOptions = {
                        path: path,
                        strokeColor: "#cccc00",
                        fillColor: "yellow",
                        editable: true
                    };
                    var polygon = new google.maps.Polygon(polygonOptions);
                    polygon.setMap(map);
                    newPolygons = polygonOptions;
                }
                path.push(event.latLng);
            });


        /*
                Basics of Google Maps API
                //add marker
                var marker = new google.maps.Marker({
                  position:{lat: 49.246292, lng: -123.116226},
                  map:map,
                  icon:'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'
                });
  
                //Displays info on marker
                var infoWindow = new google.maps.InfoWindow({
                  content: '<h1>Vancouver BC</h1>'
                });
  
                //Calls infowindow variable to display content
                marker.addListener('click', function(){
                  infoWindow.open(map,marker);
                });
  
  
        var markers = [{
            coords: {
              lat: 49.246292,
              lng: -123.116226
            },
            iconImage: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
            description: "<h1>Vancouver</h1>"
          },
          {
            coords: {
              lat: 49.1967,
              lng: -123.1815
            },
            description: "<h1>Vancouver - Airport</h1>"
          }
        ];
  
        // //Looks through markers array and adds markers to map
        // for(var i = 0; i < markers.length; i++){
        //   addMarker(markers[i]);
        // }
        //
        // //Add Marker Function
        // function addMarker(props){
        //   var marker = new google.maps.Marker({
        //     position:props.coords,
        //     map:map,
        //   });
        //
        //   if(props.iconImage){
        //     marker.setIcon(props.iconImage);
        //   }
        //
        //   if(props.description){
        //     var infoWindow = new google.maps.InfoWindow({
        //       content: props.description
        //     });
        //
        //     marker.addListener('click', function(){
        //       infoWindow.open(map, marker);
        //     });
        //   }
        // }
        */
    }

    /*
    //Initial Map
    function initMap() {

      if(localStorage["mapPolygon"] && localStorage["mapOptions"]){
        city = finalvalue.name;
        description = finalvalue.description;

        console.log(city);
        console.log(description);

        console.log("It exists!");
        newOptions = JSON.parse(localStorage["mapOptions"]);
        coords = JSON.parse(localStorage["mapPolygon"]);

        console.log(coords);
        //create map
         map = new google.maps.Map(document.getElementById('map'), newOptions);
         var polygonOptions = {
           paths: coords,
           strokeColor: '#cccc00',
           strokeOpacity: 1.0,
           strokeWeight: 3,
           fillColor: 'yellow',
           fillOpacity: 0.05,
         }
        var polygon = new google.maps.Polygon(polygonOptions);
        polygon.setMap(map);
            var path = polygon.getPath();
        // Listen from click on map
        google.maps.event.addListener(polygon, 'click', function (event) {
            debugger
            console.log("CLICKED");

            var polygonOptions = {
              path: path,
              strokeColor: "#cccc00",
              fillColor: "yellow",
              editable: true
            };
            var polygon = new google.maps.Polygon(polygonOptions);
            polygon.setMap(map);
            newPolygons = polygonOptions;
          });


        newPolygons = polygonOptions;

        //Show Name and Description on Click
        polygon.addListener('click', function(event) {
          infoWindow = new google.maps.InfoWindow;
          infoWindow.setContent("<b>" + city + "</b><br />" + description);
          infoWindow.setPosition(event.latLng);
          infoWindow.open(map);
        });
      }

      else{

      console.log("Doesn't Exist");
      //map options
      var defaultOptions = {
        zoom: 3,
        center: {
          lat: 0,
          lng: 0
        }
      }

      //create map
      map = new google.maps.Map(document.getElementById('map'), defaultOptions);

      //polygon defaults
      poly = new google.maps.Polyline({
        strokeColor: '#cccc00',
        strokeOpacity: 1.0,
        strokeWeight: 3,
        fillColor: 'yellow',
        fillOpacity: 0.05
      });
      poly.setMap(map);


      // Listen from click on map
      google.maps.event.addListener(map, 'click',
        function(event) {
          debugger
          var path = poly.getPath();
            console.log("test");

          //creates polygon once 5 points are chosen
          if (path.length == 4) {
            var polygonOptions = {
              path: path,
              strokeColor: "#cccc00",
              fillColor: "yellow",
              editable: true
            };
            var polygon = new google.maps.Polygon(polygonOptions);
            polygon.setMap(map);
            newPolygons = polygonOptions;
          }
          path.push(event.latLng);
              });
          */


      /*
              Basics of Google Maps API
              //add marker
              var marker = new google.maps.Marker({
                position:{lat: 49.246292, lng: -123.116226},
                map:map,
                icon:'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'
              });

              //Displays info on marker
              var infoWindow = new google.maps.InfoWindow({
                content: '<h1>Vancouver BC</h1>'
              });

              //Calls infowindow variable to display content
              marker.addListener('click', function(){
                infoWindow.open(map,marker);
              });


      var markers = [{
          coords: {
            lat: 49.246292,
            lng: -123.116226
          },
          iconImage: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
          description: "<h1>Vancouver</h1>"
        },
        {
          coords: {
            lat: 49.1967,
            lng: -123.1815
          },
          description: "<h1>Vancouver - Airport</h1>"
        }
      ];

      // //Looks through markers array and adds markers to map
      // for(var i = 0; i < markers.length; i++){
      //   addMarker(markers[i]);
      // }
      //
      // //Add Marker Function
      // function addMarker(props){
      //   var marker = new google.maps.Marker({
      //     position:props.coords,
      //     map:map,
      //   });
      //
      //   if(props.iconImage){
      //     marker.setIcon(props.iconImage);
      //   }
      //
      //   if(props.description){
      //     var infoWindow = new google.maps.InfoWindow({
      //       content: props.description
      //     });
      //
      //     marker.addListener('click', function(){
      //       infoWindow.open(map, marker);
      //     });
      //   }
      // }
      }
    }
    */
    // $(function() {

    //   $("#citynameInput").val(finalvalue.name);
    //   $("#descriptionInput").val(finalvalue.description);

    // });
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCROEB3riRr0oF3XNPfS-o3iL7MOEck90I&callback=initMap" async defer></script>
{% endblock %}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

<button type="button" class="btn btn-primary" onclick="addUser()">test</button>

<script>
    function addUser(){
        $.ajax({
            "type": "POST",
            "url": "/purchase/",
            "data": {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                username: 'test',
                locationName:'Seattle'
            },
            "success": function (result) {
                console.log(result);
            },
            "error": function (xhr, status, error) {
                console.log(xhr);
                console.log(status);
                console.log(error);
            },
        });
    }
</script>
{% endblock %}

app/templates/app/city.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{city}}</h2>

<div class="row">
    <img src="{{city.img}}">
    <div>{{city.description}}</div>
</div>
{% endblock %}

app/templates/app/cityeditform.html
{% extends "app/layout.html" %}

{% block content %}

<div class="row">
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        {% include 'app/form-template.html' %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

app/templates/app/form-edit-template.html
<style>
    #id_description {
        max-height: 60px;
        width: 620px;
    }
</style>
<li class="list-group-item">
        <div>
            <span class="text-danger small">{{form.name.errors}}</span>
        </div>
        <div class="input-group">
            <span class="input-group-addon">{{form.name.label_tag}}</span>
            <div>{{form.name}}</div>
        </div>
</li>
<li class="list-group-item">
        <div>
            <span class="text-danger small">{{form.description.errors}}</span>
        </div>
        <div class="input-group">
            <span class="input-group-addon">{{form.description.label_tag}}</span>
            <div>{{form.description}}</div>
        </div>
</li><li class="list-group-item">
        <div>
            <span class="text-danger small">{{form.adminuser.errors}}</span>
        </div>
        <div class="input-group">
            <span class="input-group-addon">{{form.adminuser.label_tag}}</span>
            <div>{{form.adminuser}}</div>
        </div>
</li><li class="list-group-item">
        <div>
            <span class="text-danger small">{{form.price.errors}}</span>
        </div>
        <div class="input-group">
            <span class="input-group-addon">{{form.price.label_tag}}</span>
            <div>{{form.price}}</div>
        </div>
</li><li class="list-group-item">
        <div>
            <span class="text-danger small">{{form.visibility.errors}}</span>
        </div>
        <div class="input-group">
            <span class="input-group-addon">{{form.visibility.label_tag}}</span>
            <div class="form-control" type="checkbox">{{form.visibility}}</div>
        </div>
</li>

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="container" id="carouselCont">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src="https://www.w3schools.com/bootstrap/la.jpg" alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
          <h3>Los Angeles</h3>
          <p>LA is always so much fun!</p>
        </div>
      </div>

      <div class="item">
        <img src="https://www.w3schools.com/bootstrap/chicago.jpg" alt="Chicago" style="width:100%;">
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago!</p>
        </div>
      </div>
    
      <div class="item">
        <img src="https://www.w3schools.com/bootstrap/ny.jpg" alt="New York" style="width:100%;">
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>We love the Big Apple!</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<script>
  console.log("{{ title }}");
</script>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}" />
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top navbarStyle">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Simple City Tours</a>
            </div>
            <div class="navbar-collapse collapse">
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}
        <hr />
        <footer id="myFooter">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h2 class="logo"><a href="#">   SCT</a></h2>
                    </div>

                    <div class="col-md-4">
                        <div class="social-networks">
                            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                        </div>
                        <button type="button" class="btn btn-default">Contact us</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    {% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/locations.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>

<div class="row">
    <ul>
        {% for item in  locations %}
        <li>
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6 cityDiv">
                <img src="{{ item.img }}" class="img-responsive img-thumbnail CityPic">
                <div class="middle">
                    <a href="{% url 'cityUpdateAdmin' item.id %}"><span type="button" class="btn btn-primary editBut" id="vancouverBut"><span class="glyphicon glyphicon-edit"></span>Edit</span></a>
                    <input type="checkbox" checked data-toggle="toggle">
                </div>
                <h2 class="text-center cityText ">{{item.name}}</h2>
            </div>
        </li>
        {% empty %}
        <li>No Cities yet.</li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

app/templates/app/userCreation.html
{% extends "app/layout.html" %}

{% block content %}

<div class="row">
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        {% include 'app/form-template.html' %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>

<!--<h2>{{ title }}</h2>

<div class="row">
    <div class="col-md-offset-3 col-md-6 align-items-center justify-content-center loginContainer">
        <h2 class="loginFont">{{ title }}</h2>
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <hr />
                <div class="form-group">
                    <label for="id_email" class="col-md-3 control-label loginFont">Email</label>
                    <div class="col-md-9">
                        <input class="col-md-12"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_username" class="col-md-3 control-label loginFont">Username</label>
                    <div class="col-md-9">
                        <input class="col-md-12" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-3 control-label loginFont">Password</label>
                    <div class="col-md-9">
                        <input class="col-md-12" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Create User" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
</div>-->

{% endblock %}